<a href="https://colab.research.google.com/github/angon1/ds_az/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
np.__version__


'1.21.6'

In [ ]:
example_array= np.array([1,2,3,4,5])
print(example_array)
type(example_array)
print(
    example_array.ndim, "\n",
    example_array.shape,"\n",
    example_array.size, "\n",
    example_array.dtype,"\n",
  )



2d array

In [ ]:
row_1, row_2 = [1,2], [-2,-1]
ar_2d = np.array([row_1, row_2])

In [ ]:
print(ar_2d.shape)

In [ ]:
row_1, row_2 = [1,2, 7, 2], [-2,-1, 1, 3]
ar_2d = np.array([row_1, row_2])
print(ar_2d.shape)
print(ar_2d)

In [ ]:
print(ar_2d[0][3])

3d array

In [ ]:
list_1, list_2 = [1,2,3], [4,5,6]
nested_list_1 = [list_1, list_2, list_1]
nested_list_2 = [list_2, list_1, list_2]
list_nested_nested = [nested_list_1, nested_list_2]
arr_3d = np.array(list_nested_nested)
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [1 2 3]]

 [[4 5 6]
  [1 2 3]
  [4 5 6]]]


In [ ]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]],

       [[4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [ ]:
# get 3 from arr_3d
print(arr_3d[0][2][2])
#get 6 from second value
print(arr_3d[1][0][2])

Mnożenie macierzy

In [ ]:
x = np.array([[1,2], [-3,0]])
y = np.array([[6,2], [-1,8]])
np.dot(x,y)

In [ ]:
# Generowanie list pseudolosowych
np.random.seed(0)

print(np.random.randn())
print(np.random.randn())
print(np.random.randn())


In [ ]:
np.random.randn(4,10)

In [ ]:
np.random.randn(10,4)

In [ ]:
np.random.rand(10,2,3)

In [5]:
arr_1 = np.arange(20)
arr_1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
arr_1 = arr_1.reshape(4,5)

In [8]:
arr_1[2][4]

14

In [9]:
arr_1


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
# arr wiersz, kolumna
arr_1[1:4, 0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [14]:
arr_1[1,2] =999
arr_1


array([[  0,   1,   2,   3,   4],
       [  5,   6, 999,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [15]:
# zmiana rozmiaru
arr_1.reshape(5,4)

array([[  0,   1,   2,   3],
       [  4,   5,   6, 999],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19]])

In [16]:
# wypłaszczenie
arr_1.ravel()

array([  0,   1,   2,   3,   4,   5,   6, 999,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [17]:
# transpozycja macierzy
arr_1.T

array([[  0,   5,  10,  15],
       [  1,   6,  11,  16],
       [  2, 999,  12,  17],
       [  3,   8,  13,  18],
       [  4,   9,  14,  19]])

In [22]:
arr_2 = np.arange(start=-10, stop=10, step=0.5)
arr_2 = arr_2.reshape(10,-1)
arr_2

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [24]:
mask_bigger_then_0 = arr_2 > 0


In [25]:
arr_2[mask_bigger_then_0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [26]:
np.bitwise_and(arr_2 > -5, arr_2 < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
arr_2[np.bitwise_and(arr_2 > -5, arr_2 < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])