<a href="https://colab.research.google.com/github/angon1/ds_az/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__


In [ ]:
example_array= np.array([1,2,3,4,5])
print(example_array)
type(example_array)
print(
    example_array.ndim, "\n",
    example_array.shape,"\n",
    example_array.size, "\n",
    example_array.dtype,"\n",
  )



2d array

In [13]:
row_1, row_2 = [1,2], [-2,-1]
ar_2d = np.array([row_1, row_2])

In [ ]:
print(ar_2d.shape)

In [ ]:
row_1, row_2 = [1,2, 7, 2], [-2,-1, 1, 3]
ar_2d = np.array([row_1, row_2])
print(ar_2d.shape)
print(ar_2d)

In [ ]:
print(ar_2d[0][3])

3d array

In [20]:
list_1, list_2 = [1,2,3], [4,5,6]
nested_list_1 = [list_1, list_2]
nested_list_2 = [list_2, list_1]
list_nested_nested = [nested_list_1, nested_list_2]
arr_3d = np.array(list_nested_nested)
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [1 2 3]]]


In [21]:
arr_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [1, 2, 3]]])

In [22]:
# get 2 from arr_3d
print(arr_3d[0][0][1])
#get another 2
print(arr_3d[1][1][1])

2
2
