<a href="https://colab.research.google.com/github/angon1/ds_az/blob/main/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Norma wektora
import numpy as np

v1 = np.array([-1,4])
v1

array([-1,  4])

In [4]:
# Norma wektora
np.linalg.norm(v1)

4.123105625617661

In [5]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [6]:
# punkty i ich odległość
p1 = np.array([3,0])
p2 = np.array([0,4])

np.linalg.norm(p1 - p2)


5.0

In [7]:
p1 = np.array([3,0, 17])
p2 = np.array([0,4, -2])

np.linalg.norm(p1 - p2)

19.6468827043885

In [11]:
# mnożenie macierzy
matrix_1 = np.array([[5,3], [3,9]])
matrix_2 = np.array([[1], [-1]])
print(matrix_1, '\n\n\n', matrix_2)

[[5 3]
 [3 9]] 


 [[ 1]
 [-1]]


In [13]:
res_matrix = matrix_1.dot(matrix_2)
res_matrix

array([[ 2],
       [-6]])

In [14]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)
X.dot(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


array([[13,  9, -4],
       [ 6,  2, -1]])

In [15]:
# Wyznacznik macierzy
# | A |, lub det A'
A = np.array([[2, 4], [-1, 3]])
print(np.linalg.det(A))
round(np.linalg.det(A))

9.999999999999998


10

In [16]:
# Ślad macierzy - trace
# Suma elementów po przekątnej "lewa gora" -"prawy dół"
# tr()
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

In [17]:
# Macierz jednostkowa - macierz kwadratowa, gdzie współczynniki po przekątnej (i=i | x=z) są równe 1
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
# Macierz odwrotna:
# Macierz musi być kwadratowa. Macierz odwrotna to taka, gdzie AB = BA = I
A


array([[ 2,  4],
       [-1,  3]])

In [23]:
B = np.linalg.inv(A)
np.set_printoptions(precision=4, suppress=True)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [24]:
A.dot(B)


array([[1., 0.],
       [0., 1.]])

In [25]:
B.dot(A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [26]:
# Macierz transponowana
# Kolumny zamienione na wiersze i wiersze na kolumny
np.transpose(A)


array([[ 2, -1],
       [ 4,  3]])

In [27]:
B.T


array([[ 0.3,  0.1],
       [-0.4,  0.2]])

In [28]:
# Rozwiązywanie równań
# równanie:
# 2x + 4y = 10
# x - y = -1

#macierze:
""" 
A - macierz współczynników
[
  [2, 4],
  [1, -1],
]
B - wektor wyrazów wolnych (wyników równań)
[
  [10],
  [-1],
]
X - wektor niewiadomych
[
  [x],
  [y]
]
"""
A = np.array([
  [2, 4],
  [1, -1],
])
B = np.array([
  [10],
  [-1],
])
print(A)
print(B)


[[ 2  4]
 [ 1 -1]]
[[10]
 [-1]]


In [29]:
A_inv = np.linalg.inv(A)
x = A_inv.dot(B)

In [30]:
x


array([[1.],
       [2.]])